---
title: "NPS API"
author: "Sarah Pagan"
date: "2023-10-01"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(httr)
library(jsonlite)
library(dplyr)

myKey <- "oKmYKW6S1dOrI47ra4laE70chvKFy5WGV1c0Pjgo"
```

```{r}
get_NPS_activities <- function(key, activities){
  acts <- paste(activities, collapse = ",")
  url <- paste0("https://developer.nps.gov/api/v1/activities/parks?api_key=",
                key,
                "&q=",
                acts,
                "&limit=1000")
  
  query <- GET(url)
  results <- fromJSON(rawToChar(query$content))$data$parks
  
  activity <- c()
  for (i in 1:length(activities)){
    y <- rep(activities[i],
             nrow(results[[i]]))
    activity <- append(activity, y)
  }
  
  results |>
    bind_rows() |>
    cbind(activity) |>
    arrange(fullName) |>
    select(fullName, activity, states)
}
```

```{r}
a <- GET(paste0("https://developer.nps.gov/api/v1/activities?api_key=", myKey))
fromJSON(rawToChar(a$content))$data$name
```

```{r}
get_NPS_activities(myKey, c("climbing", "swimming")) |>
  group_by(fullName) |>
  filter(n() > 1) |>
  select(-activity) |>
  distinct(fullName, states)
```

```{r}
get_NPS_parks <- function(key, states = NULL){
  if(is.null(states)){
    url <- paste0("https://developer.nps.gov/api/v1/parks?api_key=",
                  key,
                  "&limit=1000")
  }
  
  if(!is.null(states)){
    url <- paste0("https://developer.nps.gov/api/v1/parks?api_key=",
                  key,
                  "&stateCode=",
                  paste(states, collapse = ","),
                  "&limit=1000")
  }

query <- GET(url)
results <- fromJSON(rawToChar(query$content))$data

results |>
  select(fullName, parkCode, states, designation, latitude, longitude)
}

NC <- get_NPS_parks(myKey, "NC")

NC

```

```{r}

get_NPS_codes <- function(key) {
  url <- paste0("https://developer.nps.gov/api/v1/parks?api_key=",
                  key,
                  "&limit=1000")
  query <- GET(url)
  results <- fromJSON(rawToChar(query$content))$data
  results |>
    select(fullName, parkCode, states)
}

get_NPS_campgrounds <- function(key, code)

url <-  "https://developer.nps.gov/api/v1/campgrounds?api_key=oKmYKW6S1dOrI47ra4laE70chvKFy5WGV1c0Pjgo&limit=1000"

url2 <- "https://developer.nps.gov/api/v1/parks?api_key=oKmYKW6S1dOrI47ra4laE70chvKFy5WGV1c0Pjgo&limit=1000"

park_names <- fromJSON(rawToChar(GET(url2)$content))$data |>
  select(fullName, parkCode)

parks <- fromJSON(rawToChar(GET(url)$content))$data |>
  select(name, parkCode) |>
  left_join(park_names)

parks

results <- cbind(parks, fromJSON(rawToChar(GET(url)$content))$data$amenities)

results


```

```{r}
library(ggplot2)
library(sf)

NC <- NC |>
  mutate(long = as.numeric(longitude), .keep = "unused") |>
  mutate(lat = as.numeric(latitude), .keep = "unused") |>
  filter(parkCode != "trte", parkCode != "appa")

NC

nc <- st_read(system.file("shape/nc.shp", package="sf"))
ggplot(nc) +
  geom_sf(color = "darkgreen", fill = "white", size = 10) +
  geom_point(data = NC, mapping = aes(x = long, y = lat)) +
  ggrepel::geom_text_repel(data = NC, aes(x = long, y = lat, label = parkCode)) +
  theme_minimal() +
  labs(title = "Parks in North Carolina") +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab(NULL) + ylab(NULL)

```

